apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-listener" (include "refinery.fullname" .) }}
  labels: {{- include "refinery.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: listener
    {{- with .Values.refinery.common.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.refinery.listener.service.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
  annotations:
    prometheus.io/scrape: {{ required ".Values.refinery.listener.prometheus.enabled is required!" .Values.refinery.listener.prometheus.enabled | quote }}
    prometheus.io/port: {{ required ".Values.refinery.listener.bindPort is required!" .Values.refinery.listener.bindPort | quote }}
    {{- with .Values.refinery.common.annotations }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.refinery.listener.service.annotations }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
spec:
  type: {{ required ".Values.refinery.listener.service.type is required!" .Values.refinery.listener.service.type }}
  {{- with .Values.refinery.listener.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range . }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if and (eq "LoadBalancer" .Values.refinery.listener.service.type) .Values.refinery.listener.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.refinery.listener.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: srv-bnd
      port: {{ required ".Values.refinery.listener.bindPort is required!" .Values.refinery.listener.bindPort }}
      targetPort: srv-bnd
      {{- if and (eq "NodePort" .Values.refinery.listener.service.type) .Values.refinery.listener.nodePort }}
      nodePort: {{ .Values.refinery.listener.nodePort }}
      {{- end }}
  selector: {{- include "refinery.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: listener
