apiVersion: v1
kind: Secret
metadata:
  name: {{ template "refinery.fullname" . }}
  labels: {{- include "refinery.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: global
    {{- with .Values.refinery.common.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.refinery.secret.labels }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
  {{- if or .Values.refinery.common.annotations .Values.refinery.secret.annotations }}
  annotations:
    {{- with .Values.refinery.common.annotations }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
    {{- with .Values.refinery.secret.annotations }}
    {{- toYaml . | trim | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  amqpDomainEventsUser: {{ required ".Values.refinery.domain.server.amqp.events.user is required!" .Values.refinery.domain.server.amqp.events.user | b64enc }}
  