name: Docker Build/Publish Image
on:
  push:
    tags:
      - '**'
env:
  TARGET: aarch64-unknown-linux-gnu
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          rustup target add ${{ env.TARGET }}
          cargo build --release --target ${{ env.TARGET }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: refinery-binary
          path: target/${{ env.TARGET }}/release/refinery
  docker:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: refinery-binary
          path: target/release/
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: false
          tags: kami/refinery:latest
